apiVersion: apps/v1
kind: Deployment
metadata:
  name: vjailbreak-ui
  namespace: migration-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vjailbreak-ui
  template:
    metadata:
      labels:
        app: vjailbreak-ui
    spec:
      serviceAccountName: migration-controller-manager
      containers:
        - name: vjailbreak-ui-container
          image: quay.io/platform9/vjailbreak-ui:4287-139401d4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
          - name: nginx-shadow-htpasswd
            mountPath: /etc/nginx/shadow 
      volumes:
      - name: nginx-shadow-htpasswd
        hostPath:
          path: /etc/htpasswd
          type: FileOrCreate
---