---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.1
  name: vmwaremachines.vjailbreak.k8s.pf9.io
spec:
  group: vjailbreak.k8s.pf9.io
  names:
    kind: VMwareMachine
    listKind: VMwareMachineList
    plural: vmwaremachines
    singular: vmwaremachine
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VMwareMachine is the Schema for the vmwaremachines API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: VMwareMachineSpec defines the desired state of VMwareMachine
            properties:
              targetFlavorId:
                description: TargetFlavorId is the flavor to be used to create the
                  target VM on openstack
                type: string
              vms:
                description: VMInfo is the info of the VMs in the VMwareMachine
                properties:
                  clusterName:
                    description: ClusterName is the name of the cluster
                    type: string
                  cpu:
                    description: CPU is the number of CPUs in the virtual machine
                    type: integer
                  datastores:
                    description: Datastores is the list of datastores for the virtual
                      machine
                    items:
                      type: string
                    type: array
                  disks:
                    description: Disks is the list of disks for the virtual machine
                    items:
                      type: string
                    type: array
                  esxiName:
                    description: ESXiName is the name of the ESXi host
                    type: string
                  ipAddress:
                    description: IPAddress is the IP address of the virtual machine
                    type: string
                  memory:
                    description: Memory is the amount of memory in the virtual machine
                    type: integer
                  name:
                    description: Name is the name of the virtual machine
                    type: string
                  networks:
                    description: Networks is the list of networks for the virtual
                      machine
                    items:
                      type: string
                    type: array
                  osType:
                    description: OSType is the OS type of the virtual machine
                    type: string
                  vmState:
                    description: VMState is the state of the virtual machine
                    type: string
                required:
                - name
                type: object
            type: object
          status:
            description: VMwareMachineStatus defines the observed state of VMwareMachine
            properties:
              migrated:
                default: false
                description: Migrated flag to indicate if the VMs have been migrated
                type: boolean
              powerState:
                description: PowerState is the state of the VMs in the VMware
                type: string
            required:
            - migrated
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
