---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.1
  name: vmwaremachines.vjailbreak.k8s.pf9.io
spec:
  group: vjailbreak.k8s.pf9.io
  names:
    kind: VMwareMachine
    listKind: VMwareMachineList
    plural: vmwaremachines
    singular: vmwaremachine
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          VMwareMachine is the Schema for the vmwaremachines API that represents a virtual machine
          in the VMware source environment targeted for migration. It tracks VM configuration,
          resource allocation, migration status, and target environment specifications.
          VMwareMachine resources are the primary workloads migrated from VMware to OpenStack
          as part of the migration process and contain all necessary information to recreate
          equivalent virtual machines in the target environment.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: VMwareMachineSpec defines the desired state of VMwareMachine
            properties:
              targetFlavorId:
                description: TargetFlavorId is the flavor to be used to create the
                  target VM on openstack
                type: string
              vms:
                description: VMInfo is the info of the VMs in the VMwareMachine
                properties:
                  assignedIp:
                    description: AssignedIp is the IP address assigned to the VM
                    type: string
                  clusterName:
                    description: ClusterName is the name of the cluster
                    type: string
                  cpu:
                    description: CPU is the number of CPUs in the virtual machine
                    type: integer
                  datastores:
                    description: Datastores is the list of datastores for the virtual
                      machine
                    items:
                      type: string
                    type: array
                  disks:
                    description: Disks is the list of disks for the virtual machine
                    items:
                      description: Disk represents a virtual disk attached to a virtual
                        machine
                      properties:
                        capacityGB:
                          type: integer
                        datastore:
                          type: string
                        datastoreId:
                          type: string
                        name:
                          type: string
                      type: object
                    type: array
                  esxiName:
                    description: ESXiName is the name of the ESXi host
                    type: string
                  gpu:
                    description: GPU contains information about GPU devices attached
                      to the VM
                    properties:
                      passthroughCount:
                        description: PassthroughCount is the number of PCI passthrough
                          GPU devices
                        type: integer
                      vgpuCount:
                        description: VGPUCount is the number of vGPU (shared GPU)
                          devices
                        type: integer
                    type: object
                  guestNetworks:
                    description: GuestNetworks is the list of network interfaces for
                      the virtual machine as reported by the guest
                    items:
                      description: GuestNetwork represents a network interface as
                        reported by the guest.
                      properties:
                        device:
                          type: string
                        dns:
                          items:
                            type: string
                          type: array
                        ip:
                          type: string
                        mac:
                          type: string
                        origin:
                          type: string
                        prefixLength:
                          format: int32
                          type: integer
                      type: object
                    type: array
                  ipAddress:
                    description: IPAddress is the IP address of the virtual machine
                    type: string
                  memory:
                    description: Memory is the amount of memory in the virtual machine
                    type: integer
                  name:
                    description: Name is the name of the virtual machine
                    type: string
                  networkInterfaces:
                    description: NetworkInterfaces is the list of network interfaces
                      for the virtual machine expect the lo device
                    items:
                      description: NIC represents a Virtual ethernet card in the virtual
                        machine.
                      properties:
                        ipAddress:
                          type: string
                        mac:
                          type: string
                        network:
                          type: string
                        order:
                          type: integer
                      type: object
                    type: array
                  networks:
                    description: Networks is the list of networks for the virtual
                      machine
                    items:
                      type: string
                    type: array
                  osFamily:
                    description: OSFamily is the OS family of the virtual machine
                    type: string
                  rdmDisks:
                    description: RDMDisks is the list of RDM disks for the virtual
                      machine
                    items:
                      type: string
                    type: array
                  vmState:
                    description: VMState is the state of the virtual machine
                    type: string
                required:
                - name
                type: object
            type: object
          status:
            description: VMwareMachineStatus defines the observed state of VMwareMachine
            properties:
              migrated:
                default: false
                description: Migrated flag to indicate if the VMs have been migrated
                type: boolean
              powerState:
                description: PowerState is the state of the VMs in the VMware
                type: string
            required:
            - migrated
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
